version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1q2w3E*
    ports:
      - "5432:5432"
    networks:
      - talkie_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1q2w3E*
    ports:
      - "5050:80"
    networks:
      - talkie_network
    depends_on:
      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    command: >
      start-dev
      --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - 44377:8080
    networks:
      - talkie_network

  channel-service:
    build:
      context: services/Channel/src/
      dockerfile: Channel.Api/Dockerfile
      no_cache: true
    container_name: channel-service
    ports:
      - "44378:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Authentication__BaseUrl=http://keycloak:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ChannelsDb;Username=admin;Password=1q2w3E*
    networks:
      - talkie_network
    depends_on:
      - keycloak
      - postgres

networks:
  talkie_network:
    driver: bridge
